apiVersion: v1
kind: Service
metadata:
  name: {{ include "voike.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "voike.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "voike.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: doh
      port: 8053
      targetPort: doh
    - name: dns
      port: 1053
      targetPort: dns
      protocol: TCP
    - name: dns-udp
      port: 1053
      targetPort: dns-udp
      protocol: UDP
    - name: dot
      port: 8853
      targetPort: dot
